# Generated by Django 5.0.6 on 2024-05-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kreator',
            name='idkor',
            field=models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='profiles.registrovanikorisnik'),
        ),
        migrations.AlterField(
            model_name='kupac',
            name='idkor',
            field=models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='profiles.registrovanikorisnik'),
        ),
    ]
