# Generated by Django 4.2.13 on 2024-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovanikorisnik',
            name='brojkartice',
            field=models.CharField(db_column='BrojKartice', max_length=16),
        ),
    ]
