# Generated by Django 4.2.13 on 2024-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izlozba',
            name='opis',
            field=models.CharField(blank=True, db_column='Opis', max_length=1024, null=True),
        ),
    ]
