# Generated by Django 4.2.13 on 2024-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='opis',
            field=models.CharField(db_column='Opis', max_length=1024),
        ),
    ]
