# Generated by Django 5.0.6 on 2024-05-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zahtevzaregistraciju',
            options={'managed': True},
        ),
    ]
