# Generated by Django 5.0.6 on 2024-05-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idkor', models.AutoField(db_column='IdKor', primary_key=True, serialize=False)),
                ('korime', models.CharField(db_column='KorIme', max_length=32)),
                ('sifra', models.CharField(db_column='Sifra', max_length=32)),
            ],
            options={
                'db_table': 'korisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listanft',
            fields=[
                ('idlis', models.AutoField(db_column='IdLis', primary_key=True, serialize=False)),
                ('ukupnavrednost', models.FloatField(db_column='UkupnaVrednost')),
                ('brojnft', models.IntegerField(db_column='BrojNFT')),
            ],
            options={
                'db_table': 'listanft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kreator',
            fields=[
                ('idkor', models.IntegerField(db_column='IdKor', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kreator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('idkor', models.IntegerField(db_column='IdKor', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kupac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('idnft', models.AutoField(db_column='IdNFT', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=20)),
                ('vrednost', models.FloatField(db_column='Vrednost')),
                ('prosecnaocena', models.DecimalField(db_column='ProsecnaOcena', decimal_places=0, max_digits=10)),
                ('opis', models.CharField(db_column='Opis', max_length=18)),
                ('slika', models.TextField(db_column='Slika')),
            ],
            options={
                'db_table': 'nft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zahtevzaregistraciju',
            fields=[
                ('idzah', models.AutoField(db_column='IdZah', primary_key=True, serialize=False)),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('brojtelefona', models.CharField(db_column='BrojTelefona', max_length=20)),
                ('datumrodjenja', models.DateTimeField(db_column='DatumRodjenja')),
                ('mestorodjenja', models.CharField(db_column='MestoRodjenja', max_length=20)),
                ('brojkartice', models.DecimalField(db_column='BrojKartice', decimal_places=0, max_digits=10)),
                ('uloga', models.CharField(blank=True, db_column='Uloga', max_length=11, null=True)),
            ],
            options={
                'db_table': 'zahtevzaregistraciju',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.korisnik')),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrovanikorisnik',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.korisnik')),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('brojtelefona', models.CharField(db_column='BrojTelefona', max_length=20)),
                ('datumrodjenja', models.DateTimeField(db_column='DatumRodjenja')),
                ('mestorodjenja', models.CharField(db_column='MestoRodjenja', max_length=20)),
                ('brojkartice', models.DecimalField(db_column='BrojKartice', decimal_places=0, max_digits=10)),
                ('slika', models.TextField(db_column='Slika')),
            ],
            options={
                'db_table': 'registrovanikorisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Izloba',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
                ('naziv', models.CharField(blank=True, db_column='Naziv', max_length=18, null=True)),
                ('datumkreiranja', models.CharField(blank=True, db_column='DatumKreiranja', max_length=18, null=True)),
                ('prosecnaocena', models.CharField(blank=True, db_column='ProsecnaOcena', max_length=18, null=True)),
            ],
            options={
                'db_table': 'izložba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kolekcija',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
            ],
            options={
                'db_table': 'kolekcija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
            ],
            options={
                'db_table': 'portfolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pripada',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
            ],
            options={
                'db_table': 'pripada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kolekcionar',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.registrovanikorisnik')),
            ],
            options={
                'db_table': 'kolekcionar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.registrovanikorisnik')),
                ('ocena', models.IntegerField(db_column='Ocena')),
            ],
            options={
                'db_table': 'ocena',
                'managed': False,
            },
        ),
    ]
