# Generated by Django 5.0.6 on 2024-05-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izlozba',
            fields=[
                ('idlis', models.OneToOneField(db_column='IdLis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exhibitions.listanft')),
                ('naziv', models.CharField(blank=True, db_column='Naziv', max_length=18, null=True)),
                ('datumkreiranja', models.CharField(blank=True, db_column='DatumKreiranja', max_length=18, null=True)),
                ('prosecnaocena', models.CharField(blank=True, db_column='ProsecnaOcena', max_length=18, null=True)),
            ],
            options={
                'db_table': 'izložba',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='idkor',
        ),
        migrations.RemoveField(
            model_name='izloba',
            name='idlis',
        ),
        migrations.RemoveField(
            model_name='kolekcionar',
            name='idkor',
        ),
        migrations.RemoveField(
            model_name='registrovanikorisnik',
            name='idkor',
        ),
        migrations.DeleteModel(
            name='Kreator',
        ),
        migrations.DeleteModel(
            name='Kupac',
        ),
        migrations.DeleteModel(
            name='Nft',
        ),
        migrations.RemoveField(
            model_name='ocena',
            name='idkor',
        ),
        migrations.DeleteModel(
            name='Zahtevzaregistraciju',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Izloba',
        ),
        migrations.DeleteModel(
            name='Kolekcionar',
        ),
        migrations.DeleteModel(
            name='Korisnik',
        ),
        migrations.DeleteModel(
            name='Ocena',
        ),
        migrations.DeleteModel(
            name='Registrovanikorisnik',
        ),
    ]
