# Generated by Django 4.2.13 on 2024-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_korisnik_options_remove_korisnik_korime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahtevzaregistraciju',
            name='brojkartice',
            field=models.CharField(db_column='BrojKartice', max_length=16),
        ),
    ]
